project_id = "itqan-lite-phase-1-rls"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000
auto_expose_new_tables = true

[db]
port = 54322
shadow_port = 54320
health_timeout = "2m"
major_version = 17

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = false
sql_paths = []

[realtime]
enabled = false

[studio]
enabled = false

[local_smtp]
enabled = false

[storage]
enabled = true
file_size_limit = "3MiB"

[storage.buckets.weekly-plans]
public = false
file_size_limit = "3MiB"
allowed_mime_types = ["image/png", "image/jpeg", "application/pdf"]

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["http://127.0.0.1:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false
minimum_password_length = 6

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_password_change = false
max_frequency = "1s"
otp_length = 6
otp_expiry = 3600

[analytics]
enabled = false

[edge_runtime]
enabled = false
